name = "ClarabelBenchmarks"
uuid = "086be79b-982c-4ee0-9f3a-5052a7be4b8e"
version = "0.1.0"

[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
ClarabelRs = "a0c58a0a-712c-48b7-9fd4-64369ecb2011"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ConicBenchmarkUtilities = "e95a7839-07fb-532d-9a0e-071766bb5168"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[compat]
DataFrames = "1.5"
